# Reusable block: FQDN → IP mappings for /etc/hosts in every container
x-extra-hosts: &extra_hosts
  - "ldap ldap.local.lab ldap.lab.local:192.168.11.10"
  - "nfs nfs.local.lab nfs.lab.local:192.168.11.11"
  - "controller controller.local.lab controller.lab.local:192.168.11.12"
  - "ood ood.local.lab ood.lab.local:192.168.11.13"

networks:
  lan_net:
    driver: macvlan
    driver_opts:
      parent: ens33            # <-- replace with your host NIC
    ipam:
      config:
        - subnet: 192.168.11.0/24
          gateway: 192.168.11.1
          ip_range: 192.168.11.0/28  # gives .10–.25; adjust as needed

services:
  ldap:
    image: ldap:setup_complete
    container_name: ldap
    hostname: ldap
    domainname: lab.local
    privileged: true                  # systemd requires this in Docker
    cgroup: host                      # let systemd manage cgroups
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: ["/sbin/init"]    
    networks:
      lan_net:
        ipv4_address: 192.168.11.10
    extra_hosts: *extra_hosts
    restart: unless-stopped

  nfs:
    image: nfs:setup_complete
    container_name: nfs
    privileged: true                   # needed for NFS kernel modules
    restart: unless-stopped
    ports:
      - "2049:2049"                     # NFS
      - "2049:2049/udp"
      - "111:111"                       # portmapper
      - "111:111/udp"
      - "32765-32768:32765-32768"       # mountd, statd, lockd
      - "32765-32768:32765-32768/udp"
    volumes:
      - /srv/nfs4/home:/home:rw
      - /srv/nfs4/scratch:/scratch:rw
    environment:
      - NFS_EXPORT_0=/home *(rw,sync,no_subtree_check,no_root_squash)
      - NFS_EXPORT_0=/scratch *(rw,sync,no_subtree_check,no_root_squash)
    networks:
      lan_net:
        ipv4_address: 192.168.11.11
    extra_hosts: *extra_hosts
    restart: unless-stopped

  controller:
    image: base-ubuntu24-systemd:latest
    container_name: controller
    hostname: controller
    domainname: lab.local
    networks:
      lan_net:
        ipv4_address: 192.168.11.12
    extra_hosts: *extra_hosts
    restart: unless-stopped

  ood:
    image: base-ubuntu24-systemd:latest
    container_name: ood
    hostname: ood
    domainname: lab.local
    networks:
      lan_net:
        ipv4_address: 192.168.11.13
    extra_hosts: *extra_hosts
    # With macvlan the container already has a real LAN IP.
    # If exposing to the internet, point your firewall/NAT/public DNS to 192.168.0.13:443.
    # ports: ["443:443"]  # usually not needed with macvlan
    restart: unless-stopped
