version: "3.9"

services:
  nfs:
    image: base-ubuntu24-systemd:latest
    container_name: nfs
    privileged: true
    pid: "host"
    cgroup: "host"
    volumes:
      # This service’s private host storage
      - ${HOST_STORAGE_ROOT}/${IMAGE_NAME}/home:/home:rw
      - ${HOST_STORAGE_ROOT}/${IMAGE_NAME}/home/shared:/home/shared:rw
    # Typical for an NFS server container:
    network_mode: host
    restart: unless-stopped
