services:
  nfs:
    image: erichough/nfs-server
    container_name: nfs
    privileged: true                   # needed for NFS kernel modules
    restart: unless-stopped
    ports:
      - "2049:2049"                     # NFS
      - "2049:2049/udp"
      - "111:111"                       # portmapper
      - "111:111/udp"
      - "32765-32768:32765-32768"       # mountd, statd, lockd
      - "32765-32768:32765-32768/udp"
    volumes:
      - /srv/nfs4/home:/home:rw
      - /srv/nfs4/scratch:/scratch:rw
    environment:
      - NFS_EXPORT_0=/home *(rw,sync,no_subtree_check,no_root_squash)
      - NFS_EXPORT_0=/scratch *(rw,sync,no_subtree_check,no_root_squash)
